# Generated by Django 4.2.6 on 2025-03-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugias', models.TextField()),
                ('hospitalizacion', models.TextField()),
                ('alergias', models.TextField()),
                ('enfermedad_familiar', models.TextField()),
                ('trabajo', models.TextField()),
                ('fuma', models.TextField()),
                ('ejercicio', models.TextField()),
                ('medicamentos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.cita')),
                ('id_anamnesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_principal', models.TextField()),
                ('pruebas_complementarias', models.TextField()),
                ('interpretacion_examen', models.CharField(max_length=100)),
                ('diagnostico_final', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eps', models.CharField(max_length=100)),
                ('direccion_eps', models.CharField(max_length=100)),
                ('telefono_eps', models.CharField(max_length=15)),
                ('email_eps', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100)),
                ('descripcion_especialidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=100)),
                ('resultado_examen', models.TextField()),
                ('observacion_examen', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_formacion', models.CharField(max_length=100)),
                ('intitucion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(max_length=100)),
                ('fecha_fin', models.DateField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_tratamiento', models.CharField(max_length=100)),
                ('cantidad_total', models.CharField(max_length=100)),
                ('indicaciones_especiales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=50)),
                ('descripcion_procedimiento', models.TextField()),
                ('duracion_estimada', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=50)),
                ('ubicacion_sala', models.CharField(max_length=100)),
                ('capacidad_sala', models.CharField(max_length=100)),
                ('horario_disponible', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=10)),
                ('num_doc', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.eps')),
            ],
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ips', models.CharField(max_length=100)),
                ('direccion_ips', models.CharField(max_length=100)),
                ('telefono_ips', models.CharField(max_length=15)),
                ('email_ips', models.EmailField(max_length=100)),
                ('cargos', models.CharField(max_length=100)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.eps')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.consulta')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_expiracion', models.DateField(max_length=100)),
                ('recomendaciones_medicas', models.TextField()),
                ('id_diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.diagnostico')),
                ('mid_nombre_medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='ExploracionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_diastolica', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.PositiveIntegerField(blank=True, null=True)),
                ('inspeccion_general', models.TextField(blank=True, null=True)),
                ('cabeza_cuello', models.TextField(blank=True, null=True)),
                ('torax_pulmones', models.TextField(blank=True, null=True)),
                ('corazon', models.TextField(blank=True, null=True)),
                ('abdomen', models.TextField(blank=True, null=True)),
                ('extremidades', models.TextField(blank=True, null=True)),
                ('sistema_nervioso', models.TextField(blank=True, null=True)),
                ('id_anamnesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_trabajo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20)),
                ('puesto_empresa', models.CharField(max_length=100)),
                ('firma_empleado', models.CharField(max_length=100)),
                ('id_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.contrato')),
                ('id_especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.especialidad')),
                ('id_formacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.formacion')),
                ('id_ips', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.ips')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_examen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.examen'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_diagnostico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.diagnostico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado'),
        ),
    ]
