# Generated by Django 5.1.4 on 2025-04-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empleado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic_master_app.persona'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto_empresa',
            field=models.CharField(choices=[('it', 'IT'), ('medico', 'Médico'), ('admin', 'Administrador'), ('persona', 'persona')], default='it', max_length=50),
        ),
    ]
