# Generated by Django 5.1.4 on 2025-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0002_remove_usuario_empleado_usuario_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puesto_empresa',
            field=models.CharField(choices=[('it', 'IT'), ('medico', 'Médico'), ('admin', 'Administrador'), ('persona', 'persona'), ('auxiliar', 'Auxiliar')], default='it', max_length=50),
        ),
    ]
