# Generated by Django 5.1.7 on 2025-03-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0004_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='medicamentos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.medicamento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50),
        ),
    ]
