# Generated by Django 5.1.7 on 2025-03-25 14:49

import clinic_master_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0005_persona_is_active_alter_anamnesis_medicamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=clinic_master_app.models.user_directory_path, verbose_name='imagen'),
        ),
    ]
