# Generated by Django 5.1.7 on 2025-03-25 15:55

import clinic_master_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0006_persona_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=clinic_master_app.models.user_directory_path_1, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=clinic_master_app.models.user_directory_path, verbose_name='Imagen'),
        ),
    ]
