# Generated by Django 4.2.6 on 2025-03-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0008_alter_ips_cargos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='imagen',
            new_name='Firma',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='firma_empleado',
        ),
    ]
