# Generated by Django 4.2.6 on 2025-03-26 21:43

import clinic_master_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0011_cargo_remove_ips_cargos_ips_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='nivel_minimo',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Básico'), (2, 'Nivel 2 - Intermedio'), (3, 'Nivel 3 - Avanzado')], default=1),
        ),
        migrations.AddField(
            model_name='ips',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Básico'), (2, 'Nivel 2 - Intermedio'), (3, 'Nivel 3 - Avanzado')], default=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Firma',
            field=models.ImageField(blank=True, null=True, upload_to=clinic_master_app.models.user_directory_path, verbose_name='Firma'),
        ),
    ]
