# Generated by Django 4.2.6 on 2025-03-28 17:56

import clinic_master_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0012_cargo_nivel_minimo_ips_nivel_alter_empleado_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to=clinic_master_app.models.user_directory_path_1, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
