# Generated by Django 4.2.6 on 2025-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0014_remove_ips_cargos_remove_ips_eps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Firma',
        ),
    ]
